title: 'akagaeng.github.io'
baseurl: ''
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: 'akagaeng tech blog'
google_analytics_id: UA-112991808-1
layout_style: overflow
palette: blue
header:
  title: 'akagaeng'
  tagline: 'tech blog'
  profile_img: images/avatar.png
  background: light
  has_nav: true
  nav_links:
    - label: home
      url: /
      style: link
    - label: blog
      url: /blog/
      style: link
#    - label: favorites
#      url: /favorites/
#      style: link
    - label: about
      url: /about/
      style: link
  has_social: false
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      style: icon
      icon_class: fa-twitter
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/'
      style: icon
      icon_class: fa-instagram
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      style: icon
      icon_class: fa-github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: icon
      icon_class: fa-linkedin
      new_window: true
    - label: DEV
      url: 'https://dev.to/'
      style: icon
      icon_class: fa-dev
      new_window: true
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  trail:
    before: 4
    after: 4
footer:
  content: '&copy; All rights reserved.'
  links:
    - label: Made with Stackbit.
      url: 'https://www.stackbit.com'
      style: link
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
