title: 'akagaeng.github.io'
baseurl: ''
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: 'akagaeng tech blog'
google_analytics_id: UA-112991808-1
layout_style: overflow
palette: blue
header:
  title: 'Principles'
  tagline: 'akagaeng.github.io'
#  profile_img: images/avatar.png
  profile_img: ''
  background: light
  has_nav: true
  nav_links:
    - label: home
      url: /
      style: link
    - label: blog
      url: /blog/
      style: link
#    - label: favorites
#      url: /favorites/
#      style: link
    - label: about
      url: /about/
      style: link
  has_social: true
  social_links:
    - label: GitHub
      url: 'https://github.com/akagaeng'
      style: icon
      icon_class: fa-github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/kyeongsy'
      style: icon
      icon_class: fa-linkedin
      new_window: true
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  trail:
    before: 4
    after: 4
footer:
  content: '&copy; All rights reserved.'
  links:
    - label: Made with Stackbit.
      url: 'https://www.stackbit.com'
      style: link
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
